version: "3.9"

services:
  p_plex01:
    image: lscr.io/linuxserver/plex:latest
    container_name: p_plex01
    network_mode: host  # Recommended for DLNA and remote access
    environment:
      - PUID=1000           # your user ID (use `id -u` to find it)
      - PGID=1000           # your group ID (use `id -g` to find it)
      - VERSION=docker
      - TZ=America/New York  # change to your timezone
    volumes:
      - "/mnt/Vault/Media/Plex/config:/config"
      - "/mnt/Vault/Media/Shows:/tv/Adult Shows"
      - "/mnt/Vault/Media/Kids Shows:/tv/Kids Shows"
      - "/mnt/Vault/Media/Movies:/Movies/Adult Movies"
      - "/mnt/Vault/Media/Kids Movies:/Movies/Kids Movies"
      - "/mnt/Vault/Media/Family Movies:/Movies/Family Movies"
      - "/mnt/Vault/Media/Home Videos:/Home Videos"
    restart: unless-stopped