version: "3.8"

services: 
  p_postgres01:
    image: postgres:17
    container_name: p_postgres01
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "17501:5432"
    volumes:
      - /mnt/Vault/Files/HomeLab/Portainer/Stacks/databases/prod/postgres01/data:/var/lib/postgresql/data
      - /mnt/Vault/Files/HomeLab/Portainer/Stacks/databases/prod/postgres01/files:/mnt/files