version: "3.9"

services:
  p_kanboard01:
    image: kanboard/kanboard:latest
    container_name: p_kanboard01
    ports:
      - "10101:80"  # Change host port if needed
    volumes:
      - /mnt/Vault/Files/HomeLab/Portainer/Stacks/project_management/prod/kanboard01/data:/var/www/app/data  # SQLite DB + attachments + plugins
    restart: unless-stopped